# Generated by Django 4.2.2 on 2023-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, unique=True)),
                ('is_auto_update', models.BooleanField(default=False)),
                ('scheduling_time', models.IntegerField(default=10)),
                ('TTT', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['-line_user_id'],
            },
        ),
    ]
