# Generated by Django 4.2.2 on 2023-10-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingdata',
            name='TTT',
        ),
    ]
