# Generated by Django 4.2.2 on 2023-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HsrData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, unique=True)),
                ('id_card_number', models.TextField(blank=True, default='', max_length=15)),
                ('phone_number', models.TextField(blank=True, default='', max_length=15)),
                ('email', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-line_user_id'],
            },
        ),
    ]
