# Generated by Django 4.2.2 on 2023-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, unique=True)),
                ('notion_token', models.TextField(blank=True, null=True)),
                ('eeclass_db_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eeclass_username', models.CharField(max_length=255, null='')),
                ('eeclass_password', models.CharField(max_length=255, null='')),
            ],
            options={
                'ordering': ['-line_user_id'],
            },
        ),
    ]
