# Generated by Django 4.2.2 on 2023-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeclass_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='eeclass_db_id',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='eeclass_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='eeclass_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='notion_token',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
