name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - web_test # 或你的主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.11.0
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ncu_helper_web

      - name: Build Flutter Web
        run: flutter build web --base-href=/NCU_Student_Helper/ --no-tree-shake-icons
        working-directory: ncu_helper_web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ncu_helper_web/build/web
